site_name: apmodel
site_url: https://fedi-libs.github.io/apmodel
repo_url: https://github.com/fedi-libs/apmodel
edit_uri: edit/develop/docs/

nav:
  - Home: index.md

theme:
  name: material
  language: en
  palette:
    primary: red
    scheme: slate
    accent: purple
  features:
    - navigation.instant
    - navigation.tabs
    - tags
    - content.action.edit

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_files.py

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde